workflows:
  ios:
    name: iOS Build
    environment:
      vars:
        XCODE_SCHEME: "Runner"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_CONFIGURATION: "Release"
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
